-- MySQL Script generated by MySQL Workbench
-- Wed Dec 10 19:15:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema barbearia_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barbearia_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barbearia_bd` DEFAULT CHARACTER SET utf8 ;
USE `barbearia_bd` ;

-- -----------------------------------------------------
-- Table `barbearia_bd`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia_bd`.`tipo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `modulo_admin` VARCHAR(1) NOT NULL,
  `modulo_agendamento` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia_bd`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(20) NULL,
  `senha` VARCHAR(200) NOT NULL,
  `tipo_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_tipo_usuario_idx` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `barbearia_bd`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia_bd`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia_bd`.`servicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia_bd`.`agendamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia_bd`.`agendamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `servicos_id` INT NOT NULL,
  `data` DATE NOT NULL,
  `barbeiro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agendamentos_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_agendamentos_servicos1_idx` (`servicos_id` ASC) VISIBLE,
  INDEX `fk_agendamentos_barbeiro_idx` (`barbeiro_id` ASC) VISIBLE,
  CONSTRAINT `fk_agendamentos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `barbearia_bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamentos_servicos1`
    FOREIGN KEY (`servicos_id`)
    REFERENCES `barbearia_bd`.`servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamentos_barbeiro`
    FOREIGN KEY (`barbeiro_id`)
    REFERENCES `barbearia_bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia_bd`.`planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia_bd`.`planos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbearia_bd`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbearia_bd`.`pagamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `agendamentos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagamentos_agendamentos1_idx` (`agendamentos_id` ASC) VISIBLE,
  CONSTRAINT `fk_pagamentos_agendamentos1`
    FOREIGN KEY (`agendamentos_id`)
    REFERENCES `barbearia_bd`.`agendamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `barbearia_bd`.`tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `barbearia_bd`;
INSERT INTO `barbearia_bd`.`tipo_usuario` (`id`, `nome`, `modulo_admin`, `modulo_agendamento`) VALUES (1024, 'admin', 'S', 'S');

COMMIT;


-- -----------------------------------------------------
-- Data for table `barbearia_bd`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `barbearia_bd`;
INSERT INTO `barbearia_bd`.`usuarios` (`id`, `nome`, `telefone`, `senha`, `tipo_usuario_id`) VALUES (1024, 'admin', NULL, 'cbfb296f4c8a4035741cf74cadc294b8cb2b66dc21497443d6267897ce9e10cb1b27d62667e2cf92be9ca7bac9c483130b7d896361d4c09dfa6202b20b5463c8', 1024);

COMMIT;

